In [4]:
import numpy as np
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.array([0, 1, 2, 3, 4, 5, 6])

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
np.linspace(3,5,7)

array([3.        , 3.33333333, 3.66666667, 4.        , 4.33333333,
       4.66666667, 5.        ])

In [6]:
np.linspace(5,15, 5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [7]:
np.linspace(5,15, 5, endpoint=True)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [8]:
np.random.random(5)

array([0.70915158, 0.62609874, 0.67173885, 0.4501717 , 0.41141884])

In [9]:
np.random.random(5)

array([0.27729037, 0.11718868, 0.32769872, 0.92707431, 0.64011843])

In [12]:
np.random.random((5,1))

array([[0.96953662],
       [0.00881281],
       [0.93746076],
       [0.82199458],
       [0.52147581]])

In [13]:
np.random.random((1,5))

array([[0.87464811, 0.76930896, 0.73375802, 0.74831828, 0.26665824]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a.shape

(4, 4)

In [4]:

a=([range(i, i + 3) for i in [3, 6, 9]])
a

[range(3, 6), range(6, 9), range(9, 12)]

In [6]:
import numpy as np
np.array([range(i, i + 3) for i in [3, 6, 9]])

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
a = np.array([[1, 7, 3], [4, 8, 6]], int)
np.ones_like(a) 

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[2,2]

9

In [16]:
a[2,1]

8

In [17]:
a[2,2,2]

IndexError: too many indices for array

In [18]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [19]:
a[:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
a[:2,2]

array([3, 5])

In [21]:
a[:2,1]

array([2, 4])

In [22]:
a[:1,1::]

array([[2, 3]])

In [23]:
a[:3]

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [24]:
a[:3,:2:]

array([[1, 2],
       [3, 4],
       [4, 5]])

In [25]:
a[:3,1]

array([2, 4, 5])

In [26]:
np.array([0., 1., 2. ], dtype='int64')

array([0, 1, 2], dtype=int64)

In [27]:
np.array([0., 1., 2. ], dtype='complex')

array([0.+0.j, 1.+0.j, 2.+0.j])

In [28]:
d = np.dtype('i2')
d

dtype('int16')

In [29]:
d = np.dtype('>i2')
d

dtype('>i2')

In [30]:
a=np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [31]:
a.shape

(2, 3)

In [32]:
a.shape=(1,6)
a

array([[1, 2, 3, 3, 4, 5]])

In [33]:
a.shape=(6,1)
a

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [34]:
b = a.reshape(1,6)
b

array([[1, 2, 3, 3, 4, 5]])

In [35]:
a = np.arange(10)
a.ndim

1

In [36]:
a.reshape(5,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]],

       [[8],
        [9]]])

In [37]:
a.reshape(2,2,3)

ValueError: cannot reshape array of size 10 into shape (2,2,3)

In [39]:
a.reshape(2,5,1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [40]:
a.ndim

1

In [41]:
a.reshape(5,2,1)
a.ndim

1

In [45]:
b = np.arange(12)
b.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [46]:
b.ndim

1

In [47]:
grid= np.arange(12).reshape(2,2,3)
grid

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [48]:
x = np.array([3, 3, 3])
x

array([3, 3, 3])

In [49]:
x.reshape((1, 3))

array([[3, 3, 3]])

In [50]:
x[np.newaxis,:]

array([[3, 3, 3]])

In [51]:
x[:,np.newaxis]

array([[3],
       [3],
       [3]])